### ISSUE TITLE
future::plan(): better approach + don't use 'transparent'

### ISSUE THREAD

**Issue by HenrikBengtsson** [alexpkeil1/qgcompint#2]
Hi,

I see that you use for instance:

https://github.com/alexpkeil1/qgcompint/blob/1e835369edf2d25702ece77624148376cb536a94/R/base_boot.R#L387-L394

Please use the following instead:

```
if (parplan) {
  oplan <- future::plan(strategy = future::multisession)
  on.exit(plan(oplan), add = TRUE)
}
```

This is the proper way to do it, cf. `help("plan", package = "future")`.  It also avoids using `transparent`, which should not be used in package code and will eventually be deprecated.

**Comment by alexpkeil1** [comment]
Fixed in https://github.com/alexpkeil1/qgcompint/commit/1ecea0f20f2b4c0cf5fad99e5f1e1f45b563b57e
