### ISSUE TITLE
Tibble issue and factors cannot have spaces/characters in qgcomp.emm.noboot()

### ISSUE THREAD

**Issue by mkamenet3** [alexpkeil1/qgcompint#3]
If the modifier (a factor) has any spaces or characters in the factor label (ex: "Non-Smoker" or "New Mexico"), the `qgcomp.emm.noboot()` function throws the following error: `Error in mod$cov.scaled[emmvars[x], emmvars[x]] : subscript out of bounds`. 

Suggestion to just modify the man file to clarify this point.

Additionally, if the dataframe is a tibble, the `wgcomp.emm.noboot()` function throws the following error: `Error in model.frame.default(object, data, xlev = xlev) : 
  invalid type (list) for variable 'z'`
  
 Suggestion to also just modify the man file to clarify this point.

**Comment by alexpkeil1** [comment]
Thanks. Second issue seems fixable.

I can't recreate the first issue. Do you have a minimal working example for this. Here's mine: 

    library(qgcomp)
    library(qgcompint)
    set.seed(23)
    dat <- simdata_quantized_emm(
      outcometype="logistic",
      # sample size
      n = 100,
      # correlation between x1 and x2,x3,...
      corr=c(0.8,0.6,0.3,-0.3,-0.3,-0.3),
      # model intercept
      b0=-2,
      # linear model coefficients for x1,x2,... at referent level of interacting variable
      mainterms=c(0.3,-0.1,0.1,0.0,0.3,0.1,0.1),
      # linear model coefficients for product terms between x1,x2,... and interacting variable
      prodterms = c(1.0,0.0,0.0,0.0,0.1,0.1,0.1),
      # type of interacting variable
      ztype = "categorical",
      # number of levels of exposure
      q = 4,
      # residual variance of y
      yscale = 2.0
    )
    
    dat$zspace <- paste("cat", dat$z)
    dat$zspace <- ifelse(dat$z==1, "cat1", dat$zspace)
    
    dat$zspace2 = as.factor(dat$zspace)
    # testing with character
    qfit1 <- qgcomp.emm.noboot(y~x1+x2,
                               data = dat,
                               expnms = paste0("x",1:2),
                               emmvar = "zspace",
                               q = 4)
    # testing with factor
    qfit2 <- qgcomp.emm.noboot(y~x1+x2,
                               data = dat,
                               expnms = paste0("x",1:2),
                               emmvar = "zspace2",
                               q = 4)
    qfit1
    qfit2

**Comment by alexpkeil1** [comment]
Tentative fix for the second issue available in dev version. Install via:

`devtools::install_github("alexpkeil1/qgcompint")`

Please let me know if you try this and it does not work or cause other issues.

**Comment by mkamenet3** [comment]
Thank you for the tibble fix! The space issue was just a silly bug on my part - my bad!
